---
- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - hadolint
    gate:
      jobs:
        - flake8
        - hadolint
    periodic-daily:
      jobs:
        - flake8
        - hadolint
