---
collections:
  - name: ansible.netcommon
    version: 5.3.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.12.0
  - name: cloud.common
    version: 2.1.4
  - name: community.crypto
    version: 2.17.1
  - name: community.docker
    version: 3.7.0
  - name: community.general
    version: 7.5.4
  - name: community.grafana
    version: 1.7.0
  - name: community.hashi_vault
    version: 5.0.1
  - name: community.mysql
    version: 3.8.0
  - name: community.network
    version: 5.0.2
  - name: community.rabbitmq
    version: 1.2.3
  - name: containers.podman
    version: 1.12.0
  - name: kubernetes.core
    version: 3.0.0
  - name: netbox.netbox
    version: 3.16.0
  - name: openstack.cloud
    version: 2.2.0
