---
collections:
  - name: ansible.netcommon
    version: 7.0.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 5.1.0
  - name: cloud.common
    version: 4.0.0
  - name: community.crypto
    version: 2.21.1
  - name: community.docker
    version: 3.12.1
  - name: community.general
    version: 9.3.0
  - name: community.grafana
    version: 2.1.0
  - name: community.hashi_vault
    version: 6.2.0
  - name: community.mysql
    version: 3.9.0
  - name: community.network
    version: 5.0.3
  - name: community.rabbitmq
    version: 1.3.0
  - name: containers.podman
    version: 1.15.4
  - name: kubernetes.core
    version: 5.0.0
  - name: netbox.netbox
    version: 3.19.1
  - name: openstack.cloud
    version: 2.2.0
