---
collections:
  - name: ansible.netcommon
    version: 5.1.2
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.10.3
  - name: cloud.common
    version: 2.1.3
  - name: community.crypto
    version: 2.14.1
  - name: community.docker
    version: 3.4.8
  - name: community.general
    version: 7.2.0
  - name: community.grafana
    version: 1.5.4
  - name: community.hashi_vault
    version: 5.0.0
  - name: community.mysql
    version: 3.7.2
  - name: community.network
    version: 5.0.0
  - name: community.rabbitmq
    version: 1.2.3
  - name: containers.podman
    version: 1.10.2
  - name: kubernetes.core
    version: 2.4.0
  - name: netbox.netbox
    version: 3.13.0
  - name: openstack.cloud
    version: 2.1.0
