---
collections:
  - name: ansible.netcommon
    version: 4.1.0
  - name: ansible.posix
    version: 1.5.1
  - name: ansible.utils
    version: 2.9.0
  - name: cloud.common
    version: 2.1.2
  - name: community.crypto
    version: 2.10.0
  - name: community.docker
    version: 3.4.0
  - name: community.general
    version: 6.3.0
  - name: community.grafana
    version: 1.5.4
  - name: community.hashi_vault
    version: 4.1.0
  - name: community.mysql
    version: 3.6.0
  - name: community.network
    version: 5.0.0
  - name: community.rabbitmq
    version: 1.2.3
  - name: containers.podman
    version: 1.10.1
  - name: kubernetes.core
    version: 2.4.0
  - name: netbox.netbox
    version: 3.11.0
  - name: openstack.cloud
    version: 1.10.0
