---
collections:
  - name: ansible.netcommon
    version: 6.0.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 3.1.0
  - name: cloud.common
    version: 3.0.0
  - name: community.crypto
    version: 2.18.0
  - name: community.docker
    version: 3.8.0
  - name: community.general
    version: 8.4.0
  - name: community.grafana
    version: 1.8.0
  - name: community.hashi_vault
    version: 6.1.0
  - name: community.mysql
    version: 3.9.0
  - name: community.network
    version: 5.0.2
  - name: community.rabbitmq
    version: 1.2.3
  - name: containers.podman
    version: 1.12.0
  - name: kubernetes.core
    version: 3.0.1
  - name: netbox.netbox
    version: 3.17.0
  - name: openstack.cloud
    version: 2.2.0
