---
collections:
  - name: ansible.netcommon
    version: 6.1.3
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 4.1.0
  - name: cloud.common
    version: 4.0.0
  - name: community.crypto
    version: 2.20.0
  - name: community.docker
    version: 3.10.3
  - name: community.general
    version: 9.0.1
  - name: community.grafana
    version: 2.0.0
  - name: community.hashi_vault
    version: 6.2.0
  - name: community.mysql
    version: 3.9.0
  - name: community.network
    version: 5.0.2
  - name: community.rabbitmq
    version: 1.3.0
  - name: containers.podman
    version: 1.14.0
  - name: kubernetes.core
    version: 4.0.0
  - name: netbox.netbox
    version: 3.19.1
  - name: openstack.cloud
    version: 2.2.0
