---
collections:
  - name: ansible.netcommon
    version: 7.2.0
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: cloud.common
    version: 4.0.0
  - name: community.crypto
    version: 2.26.0
  - name: community.docker
    version: 4.5.2
  - name: community.general
    version: 10.5.0
  - name: community.grafana
    version: 2.1.0
  - name: community.hashi_vault
    version: 6.2.0
  - name: community.mysql
    version: 3.13.0
  - name: community.network
    version: 5.1.0
  - name: community.rabbitmq
    version: 1.4.0
  - name: containers.podman
    version: 1.16.3
  - name: kubernetes.core
    version: 5.1.0
  - name: netbox.netbox
    version: 3.21.0
  - name: openstack.cloud
    version: 2.4.1
