---
- name: Run integration tests
  hosts: all

  vars:
    python_venv_dir: /tmp/venv

  tasks:
    - name: Start Redis container
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: |
          set -e
          set -o pipefail
          set -x

          docker run -d --name redis -p 6379:6379 redis:7-alpine
      changed_when: true

    - name: Install dependencies
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          {{ python_venv_dir }}/bin/pipenv install --dev --deploy
          {{ python_venv_dir }}/bin/pipenv run pip install .

    - name: Run pytest
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          {{ python_venv_dir }}/bin/pipenv run pytest tests/integration
      environment:
        REDIS_HOST: localhost
