---
- name: Test python setup
  hosts: all

  tasks:
    - name: Run test script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export PATH=$PATH:$HOME/.local/bin

          pip3 install pipenv
          pipenv install
          pipenv run pip3 freeze > requirements.txt
          pip3 install .
