---
- name: Run unit tests
  hosts: all

  vars:
    python_venv_dir: /tmp/venv

  tasks:
    - name: Install dependencies
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          {{ python_venv_dir }}/bin/pipenv install --dev --deploy
          {{ python_venv_dir }}/bin/pipenv run pip install .

    - name: Run pytest
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          {{ python_venv_dir }}/bin/pipenv run pytest
