---
- name: Test python setup
  hosts: all

  vars:
    python_venv_dir: /tmp/venv

  tasks:
    - name: Run test script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          {{ python_venv_dir }}/bin/pipenv install
          {{ python_venv_dir }}/bin/pipenv run pip install --no-deps .
