---
- name: Run unit tests
  hosts: all

  tasks:
    - name: Install dependencies
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export PATH=$PATH:$HOME/.local/bin

          pipenv install --dev
          pipenv run pip install .

    - name: Run pytest
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          set -e
          set -o pipefail
          set -x

          export PATH=$PATH:$HOME/.local/bin

          pipenv run pytest
