---
name: Test netbox integration

"on":
  push:
    paths:
      - '**.py'
      - 'setup.cfg'
      - .github/workflows/test-netbox-integration.yml
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
      - 'setup.cfg'
      - .github/workflows/test-netbox-integration.yml

jobs:
  test-python-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip3 install pipenv
          pipenv install
          pipenv run pip3 freeze > requirements.txt
          pip3 install .
          pip3 install ansible~=6.6.0
          ansible-galaxy collection install https://github.com/osism/ansible-collection-services/archive/main.tar.gz
