---
name: Test python setup

"on":
  push:
    paths:
      - '**.py'
      - 'setup.cfg'
      - .github/workflows/test-python-setup.yml
    branches:
      - main
  pull_request:
    paths:
      - '**.py'
      - 'setup.cfg'
      - .github/workflows/test-python-setup.yml

jobs:
  test-python-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip3 install pipenv
          pipenv install
          pipenv run pip3 freeze > requirements.txt
          pip3 install .
